//HintName: NamedItemDataTypeMap.g.cs
#nullable enable
namespace BanjoBotAssets.Json
{
    partial class NamedItemDataConverter
    {

        /// <summary>
        /// Creates a new instance of a class derived from <see cref="NamedItemData"/> based on the value of the <c>Type</c> field.
        /// </summary>
        /// <remarks>
        /// This method is automatically generated by <see cref="NamedItemDataTypeMapGenerator"/>.
        /// </remarks>
        /// <param name="discriminator">The value of the <c>Type</c> field.</param>
        /// <returns>A new instance of a class derived from <see cref="NamedItemData"/> if one exists for the specified discriminator;
        /// otherwise, <c>null</c>.</returns>
        private static NamedItemData? CreateNamedItemDataFromTypeField(string discriminator) => discriminator switch
        {
            "Bar" => new global::BanjoBotAssets.Json.BarNamedItemData(),
            "Foo" => new global::BanjoBotAssets.Json.FooNamedItemData(),
            _ => null,
        };
    }
}
