//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanjoBotAssets.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BanjoBotAssets.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string ELanguage {
            get {
                return ResourceManager.GetString("ELanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load AES keys..
        /// </summary>
        internal static string Error_AesFetchFailed {
            get {
                return ResourceManager.GetString("Error_AesFetchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot decode texture to bitmap: {Asset}.
        /// </summary>
        internal static string Error_CannotDecodeTexture {
            get {
                return ResourceManager.GetString("Error_CannotDecodeTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot encode bitmap for export: {Asset}.
        /// </summary>
        internal static string Error_CannotEncodeTexture {
            get {
                return ResourceManager.GetString("Error_CannotEncodeTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while processing asset {Asset}.
        /// </summary>
        internal static string Error_ExceptionWhileProcessingAsset {
            get {
                return ResourceManager.GetString("Error_ExceptionWhileProcessingAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while processing asset group {AssetGroup}.
        /// </summary>
        internal static string Error_ExceptionWhileProcessingAssetGroup {
            get {
                return ResourceManager.GetString("Error_ExceptionWhileProcessingAssetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Asset}.
        /// </summary>
        internal static string Error_FailedAsset {
            get {
                return ResourceManager.GetString("Error_FailedAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download usmap from {URL}.
        /// </summary>
        internal static string Error_FailedToDownloadUsmap {
            get {
                return ResourceManager.GetString("Error_FailedToDownloadUsmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get FNCentral Mappings Endpoint.
        /// </summary>
        internal static string Error_FailedToGetMappingsEndpoint {
            get {
                return ResourceManager.GetString("Error_FailedToGetMappingsEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished with {Count} failed assets:.
        /// </summary>
        internal static string Error_FinishedWithFailedAssets {
            get {
                return ResourceManager.GetString("Error_FinishedWithFailedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find game directory. Add it to the GameDirectories setting..
        /// </summary>
        internal static string Error_GameNotFound {
            get {
                return ResourceManager.GetString("Error_GameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load mappings..
        /// </summary>
        internal static string Error_MappingsFetchFailed {
            get {
                return ResourceManager.GetString("Error_MappingsFetchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t reload mappings, json array was empty.
        /// </summary>
        internal static string Error_MissingMappingsJsonArray {
            get {
                return ResourceManager.GetString("Error_MissingMappingsJsonArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No gameplay effects in ability {Ability}.
        /// </summary>
        internal static string Error_NoGameplayEffectsInAbility {
            get {
                return ResourceManager.GetString("Error_NoGameplayEffectsInAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a manager.
        /// </summary>
        internal static string Error_NotAManager {
            get {
                return ResourceManager.GetString("Error_NotAManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find required asset: {Asset}.
        /// </summary>
        internal static string Error_SpecificAssetNotFound {
            get {
                return ResourceManager.GetString("Error_SpecificAssetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncaught exception while reloading mappings from FNCentral.
        /// </summary>
        internal static string Error_UncaughtExceptionWhileReloadingMappings {
            get {
                return ResourceManager.GetString("Error_UncaughtExceptionWhileReloadingMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected number of gadgets in ability {Ability} ({Count}).
        /// </summary>
        internal static string Error_UnexpectedNumberOfGadgetsInAbility {
            get {
                return ResourceManager.GetString("Error_UnexpectedNumberOfGadgetsInAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender.
        /// </summary>
        internal static string Field_Defender_DefaultName {
            get {
                return ResourceManager.GetString("Field_Defender_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor.
        /// </summary>
        internal static string Field_Hero_Constructor {
            get {
                return ResourceManager.GetString("Field_Hero_Constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninja.
        /// </summary>
        internal static string Field_Hero_Ninja {
            get {
                return ResourceManager.GetString("Field_Hero_Ninja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No granted ability.
        /// </summary>
        internal static string Field_Hero_NoGrantedAbility {
            get {
                return ResourceManager.GetString("Field_Hero_NoGrantedAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlander.
        /// </summary>
        internal static string Field_Hero_Outlander {
            get {
                return ResourceManager.GetString("Field_Hero_Outlander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soldier.
        /// </summary>
        internal static string Field_Hero_Soldier {
            get {
                return ResourceManager.GetString("Field_Hero_Soldier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Field_Hero_Unknown {
            get {
                return ResourceManager.GetString("Field_Hero_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description.
        /// </summary>
        internal static string Field_NoDescription {
            get {
                return ResourceManager.GetString("Field_NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        internal static string Field_Recipe_Melee {
            get {
                return ResourceManager.GetString("Field_Recipe_Melee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged.
        /// </summary>
        internal static string Field_Recipe_Ranged {
            get {
                return ResourceManager.GetString("Field_Recipe_Ranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trap.
        /// </summary>
        internal static string Field_Recipe_Trap {
            get {
                return ResourceManager.GetString("Field_Recipe_Trap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assault.
        /// </summary>
        internal static string Field_Schematic_Assault {
            get {
                return ResourceManager.GetString("Field_Schematic_Assault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axe.
        /// </summary>
        internal static string Field_Schematic_Axe {
            get {
                return ResourceManager.GetString("Field_Schematic_Axe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightcore.
        /// </summary>
        internal static string Field_Schematic_Brightcore {
            get {
                return ResourceManager.GetString("Field_Schematic_Brightcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceiling.
        /// </summary>
        internal static string Field_Schematic_Ceiling {
            get {
                return ResourceManager.GetString("Field_Schematic_Ceiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club.
        /// </summary>
        internal static string Field_Schematic_Club {
            get {
                return ResourceManager.GetString("Field_Schematic_Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copper.
        /// </summary>
        internal static string Field_Schematic_Copper {
            get {
                return ResourceManager.GetString("Field_Schematic_Copper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystal.
        /// </summary>
        internal static string Field_Schematic_Crystal {
            get {
                return ResourceManager.GetString("Field_Schematic_Crystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosive.
        /// </summary>
        internal static string Field_Schematic_Explosive {
            get {
                return ResourceManager.GetString("Field_Schematic_Explosive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        internal static string Field_Schematic_Floor {
            get {
                return ResourceManager.GetString("Field_Schematic_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handmade.
        /// </summary>
        internal static string Field_Schematic_Handmade {
            get {
                return ResourceManager.GetString("Field_Schematic_Handmade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware.
        /// </summary>
        internal static string Field_Schematic_Hardware {
            get {
                return ResourceManager.GetString("Field_Schematic_Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string Field_Schematic_Invalid {
            get {
                return ResourceManager.GetString("Field_Schematic_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malachite.
        /// </summary>
        internal static string Field_Schematic_Malachite {
            get {
                return ResourceManager.GetString("Field_Schematic_Malachite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsidian.
        /// </summary>
        internal static string Field_Schematic_Obsidian {
            get {
                return ResourceManager.GetString("Field_Schematic_Obsidian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ore.
        /// </summary>
        internal static string Field_Schematic_Ore {
            get {
                return ResourceManager.GetString("Field_Schematic_Ore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pistol.
        /// </summary>
        internal static string Field_Schematic_Pistol {
            get {
                return ResourceManager.GetString("Field_Schematic_Pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scythe.
        /// </summary>
        internal static string Field_Schematic_Scythe {
            get {
                return ResourceManager.GetString("Field_Schematic_Scythe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadowshard.
        /// </summary>
        internal static string Field_Schematic_Shadowshard {
            get {
                return ResourceManager.GetString("Field_Schematic_Shadowshard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shotgun.
        /// </summary>
        internal static string Field_Schematic_Shotgun {
            get {
                return ResourceManager.GetString("Field_Schematic_Shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        internal static string Field_Schematic_Silver {
            get {
                return ResourceManager.GetString("Field_Schematic_Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMG.
        /// </summary>
        internal static string Field_Schematic_SMG {
            get {
                return ResourceManager.GetString("Field_Schematic_SMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper.
        /// </summary>
        internal static string Field_Schematic_Sniper {
            get {
                return ResourceManager.GetString("Field_Schematic_Sniper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spear.
        /// </summary>
        internal static string Field_Schematic_Spear {
            get {
                return ResourceManager.GetString("Field_Schematic_Spear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunbeam.
        /// </summary>
        internal static string Field_Schematic_Sunbeam {
            get {
                return ResourceManager.GetString("Field_Schematic_Sunbeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sword.
        /// </summary>
        internal static string Field_Schematic_Sword {
            get {
                return ResourceManager.GetString("Field_Schematic_Sword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Field_Schematic_Unknown {
            get {
                return ResourceManager.GetString("Field_Schematic_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall.
        /// </summary>
        internal static string Field_Schematic_Wall {
            get {
                return ResourceManager.GetString("Field_Schematic_Wall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivor.
        /// </summary>
        internal static string Field_Survivor_DefaultName {
            get {
                return ResourceManager.GetString("Field_Survivor_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        internal static string Field_Survivor_Doctor {
            get {
                return ResourceManager.GetString("Field_Survivor_Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineer.
        /// </summary>
        internal static string Field_Survivor_Engineer {
            get {
                return ResourceManager.GetString("Field_Survivor_Engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        internal static string Field_Survivor_Explorer {
            get {
                return ResourceManager.GetString("Field_Survivor_Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadgeteer.
        /// </summary>
        internal static string Field_Survivor_Gadgeteer {
            get {
                return ResourceManager.GetString("Field_Survivor_Gadgeteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventor.
        /// </summary>
        internal static string Field_Survivor_Inventor {
            get {
                return ResourceManager.GetString("Field_Survivor_Inventor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marksman.
        /// </summary>
        internal static string Field_Survivor_Marksman {
            get {
                return ResourceManager.GetString("Field_Survivor_Marksman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martial Artist.
        /// </summary>
        internal static string Field_Survivor_MartialArtist {
            get {
                return ResourceManager.GetString("Field_Survivor_MartialArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer.
        /// </summary>
        internal static string Field_Survivor_Trainer {
            get {
                return ResourceManager.GetString("Field_Survivor_Trainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets.json.
        /// </summary>
        internal static string File_assets_json {
            get {
                return ResourceManager.GetString("File_assets_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExportedImages.
        /// </summary>
        internal static string File_ExportedImages {
            get {
                return ResourceManager.GetString("File_ExportedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schematics.json.
        /// </summary>
        internal static string File_schematics_json {
            get {
                return ResourceManager.GetString("File_schematics_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to merge because the previous artifact could not be read: {0}.
        /// </summary>
        internal static string FormatString_Error_CannotReadPreviousArtifact {
            get {
                return ResourceManager.GetString("FormatString_Error_CannotReadPreviousArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected manager synergy {0}.
        /// </summary>
        internal static string FormatString_Error_UnexpectedManagerSynergy {
            get {
                return ResourceManager.GetString("FormatString_Error_UnexpectedManagerSynergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string FormatString_Field_Defender_DisplayNameFormat {
            get {
                return ResourceManager.GetString("FormatString_Field_Defender_DisplayNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Defender.
        /// </summary>
        internal static string FormatString_Field_Defender_NameFormat {
            get {
                return ResourceManager.GetString("FormatString_Field_Defender_NameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead {0}.
        /// </summary>
        internal static string FormatString_Field_Survivor_LeadNameFormat {
            get {
                return ResourceManager.GetString("FormatString_Field_Survivor_LeadNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting {0}.
        /// </summary>
        internal static string FormatString_Status_ExportingGroup {
            get {
                return ResourceManager.GetString("FormatString_Status_ExportingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing file list.
        /// </summary>
        internal static string Status_AnalyzingFileList {
            get {
                return ResourceManager.GetString("Status_AnalyzingFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cached mappings to {File}.
        /// </summary>
        internal static string Status_CachedMappingsToFile {
            get {
                return ResourceManager.GetString("Status_CachedMappingsToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache miss: {Path} ({Size}).
        /// </summary>
        internal static string Status_CacheMiss {
            get {
                return ResourceManager.GetString("Status_CacheMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache size: {Size}. Hits: {Hits}. Misses: {Misses}. Hit ratio: {Ratio:0.0%}..
        /// </summary>
        internal static string Status_CacheStats {
            get {
                return ResourceManager.GetString("Status_CacheStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - ({Count}) {Path}.
        /// </summary>
        internal static string Status_CacheTopMisses_Entry {
            get {
                return ResourceManager.GetString("Status_CacheTopMisses_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top paths for cache misses:.
        /// </summary>
        internal static string Status_CacheTopMisses_Heading {
            get {
                return ResourceManager.GetString("Status_CacheTopMisses_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting game files.
        /// </summary>
        internal static string Status_DecryptingGameFiles {
            get {
                return ResourceManager.GetString("Status_DecryptingGameFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished exporting {AssetType} ({Total} assets, {Failures} failed).
        /// </summary>
        internal static string Status_ExportedGroup {
            get {
                return ResourceManager.GetString("Status_ExportedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported item ratings.
        /// </summary>
        internal static string Status_ExportedItemRatings {
            get {
                return ResourceManager.GetString("Status_ExportedItemRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported quest map.
        /// </summary>
        internal static string Status_ExportedQuestMap {
            get {
                return ResourceManager.GetString("Status_ExportedQuestMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported recipes.
        /// </summary>
        internal static string Status_ExportedRecipes {
            get {
                return ResourceManager.GetString("Status_ExportedRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting images ({ImageType}).
        /// </summary>
        internal static string Status_ExportingImagesType {
            get {
                return ResourceManager.GetString("Status_ExportingImagesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting item ratings.
        /// </summary>
        internal static string Status_ExportingItemRatings {
            get {
                return ResourceManager.GetString("Status_ExportingItemRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting quest map.
        /// </summary>
        internal static string Status_ExportingQuestMap {
            get {
                return ResourceManager.GetString("Status_ExportingQuestMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting recipes.
        /// </summary>
        internal static string Status_ExportingRecipes {
            get {
                return ResourceManager.GetString("Status_ExportingRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching AES keys from external API: {URL}.
        /// </summary>
        internal static string Status_FetchingAesFromApi {
            get {
                return ResourceManager.GetString("Status_FetchingAesFromApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {Count} assets in {TotalDuration} ({AverageDuration} ms per asset).
        /// </summary>
        internal static string Status_LoadedAssets {
            get {
                return ResourceManager.GetString("Status_LoadedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded cached mappings from {File}.
        /// </summary>
        internal static string Status_LoadedCachedMappings {
            get {
                return ResourceManager.GetString("Status_LoadedCachedMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {Count} virtual paths.
        /// </summary>
        internal static string Status_LoadedVirtualPaths {
            get {
                return ResourceManager.GetString("Status_LoadedVirtualPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading AES keys from {File}.
        /// </summary>
        internal static string Status_LoadingAesFromFile {
            get {
                return ResourceManager.GetString("Status_LoadingAesFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading localization ({Language}).
        /// </summary>
        internal static string Status_LoadingLocalization {
            get {
                return ResourceManager.GetString("Status_LoadingLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading mappings.
        /// </summary>
        internal static string Status_LoadingMappings {
            get {
                return ResourceManager.GetString("Status_LoadingMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging into existing artifact: {File}.
        /// </summary>
        internal static string Status_MergingIntoExistingArtifact {
            get {
                return ResourceManager.GetString("Status_MergingIntoExistingArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cached AES keys found at {File}.
        /// </summary>
        internal static string Status_MissingAesCache {
            get {
                return ResourceManager.GetString("Status_MissingAesCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {File} ({Number} of {Total}).
        /// </summary>
        internal static string Status_ProcessingFile {
            get {
                return ResourceManager.GetString("Status_ProcessingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {AssetType} group {Number} of {Total}.
        /// </summary>
        internal static string Status_ProcessingTypeGroupNumOfNum {
            get {
                return ResourceManager.GetString("Status_ProcessingTypeGroupNumOfNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {AssetType} {Number} of {Total}.
        /// </summary>
        internal static string Status_ProcessingTypeNumOfNum {
            get {
                return ResourceManager.GetString("Status_ProcessingTypeNumOfNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering export types.
        /// </summary>
        internal static string Status_RegisteringExportTypes {
            get {
                return ResourceManager.GetString("Status_RegisteringExportTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrying mappings.
        /// </summary>
        internal static string Status_RetryingMappings {
            get {
                return ResourceManager.GetString("Status_RetryingMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running all exporters.
        /// </summary>
        internal static string Status_RunningAllExporters {
            get {
                return ResourceManager.GetString("Status_RunningAllExporters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running {Count} exporters: {ExporterClasses}.
        /// </summary>
        internal static string Status_RunningSelectedExporters {
            get {
                return ResourceManager.GetString("Status_RunningSelectedExporters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caching AES keys in {File}.
        /// </summary>
        internal static string Status_SavingAesToFile {
            get {
                return ResourceManager.GetString("Status_SavingAesToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping {Asset} early as instructed..
        /// </summary>
        internal static string Status_SkippingEarlyAsInstructed {
            get {
                return ResourceManager.GetString("Status_SkippingEarlyAsInstructed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping gadget with no gameplay ability: {Asset}.
        /// </summary>
        internal static string Status_SkippingGadgetWithoutAbility {
            get {
                return ResourceManager.GetString("Status_SkippingGadgetWithoutAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping {Asset} late as instructed..
        /// </summary>
        internal static string Status_SkippingLateAsInstructed {
            get {
                return ResourceManager.GetString("Status_SkippingLateAsInstructed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping null {AssetType} group containing {Count} items..
        /// </summary>
        internal static string Status_SkippingNullGroup {
            get {
                return ResourceManager.GetString("Status_SkippingNullGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping null main key.
        /// </summary>
        internal static string Status_SkippingNullMainKey {
            get {
                return ResourceManager.GetString("Status_SkippingNullMainKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cached AES keys in {File} are older than game files, ignoring.
        /// </summary>
        internal static string Status_SkippingOutdatedCachedAes {
            get {
                return ResourceManager.GetString("Status_SkippingOutdatedCachedAes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cached mappings in {File} are older than game files, ignoring.
        /// </summary>
        internal static string Status_SkippingOutdatedCachedMappings {
            get {
                return ResourceManager.GetString("Status_SkippingOutdatedCachedMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping group member that failed to parse: {TemplateId} ({Metadata}).
        /// </summary>
        internal static string Status_SkippingUnparsable {
            get {
                return ResourceManager.GetString("Status_SkippingUnparsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting key for {File}.
        /// </summary>
        internal static string Status_SubmittingDynamicKey {
            get {
                return ResourceManager.GetString("Status_SubmittingDynamicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting main key.
        /// </summary>
        internal static string Status_SubmittingMainKey {
            get {
                return ResourceManager.GetString("Status_SubmittingMainKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing artifact: {File}.
        /// </summary>
        internal static string Status_WritingFreshArtifact {
            get {
                return ResourceManager.GetString("Status_WritingFreshArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrote {FileCount} image files, updated {UpdatedPathCount} paths.
        /// </summary>
        internal static string Status_WroteImageFilesUpdatedPaths {
            get {
                return ResourceManager.GetString("Status_WroteImageFilesUpdatedPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Can&apos;t parse defender name: {TemplateId}.
        /// </summary>
        internal static string Warning_CannotParseDefenderName {
            get {
                return ResourceManager.GetString("Warning_CannotParseDefenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Can&apos;t determine PL requirement from objective condition: {Expression}.
        /// </summary>
        internal static string Warning_CannotParseDifficultyCondition {
            get {
                return ResourceManager.GetString("Warning_CannotParseDifficultyCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Can&apos;t parse hero name: {TemplateId}.
        /// </summary>
        internal static string Warning_CannotParseHeroName {
            get {
                return ResourceManager.GetString("Warning_CannotParseHeroName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Can&apos;t parse schematic name: {TemplateId}.
        /// </summary>
        internal static string Warning_CannotParseSchematicName {
            get {
                return ResourceManager.GetString("Warning_CannotParseSchematicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Can&apos;t parse survivor name: {TemplateId}.
        /// </summary>
        internal static string Warning_CannotParseSurvivorName {
            get {
                return ResourceManager.GetString("Warning_CannotParseSurvivorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Could not load {Asset}.
        /// </summary>
        internal static string Warning_CouldNotLoadAsset {
            get {
                return ResourceManager.GetString("Warning_CouldNotLoadAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Could not find curve {TableRow}.
        /// </summary>
        internal static string Warning_CouldNotLoadCurveTableRow {
            get {
                return ResourceManager.GetString("Warning_CouldNotLoadCurveTableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Failed to load {File}.
        /// </summary>
        internal static string Warning_FailedToLoadFile {
            get {
                return ResourceManager.GetString("Warning_FailedToLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Ignoring unknown modify operation {ModifyOperation}.
        /// </summary>
        internal static string Warning_IgnoringUnknownModifyOperation {
            get {
                return ResourceManager.GetString("Warning_IgnoringUnknownModifyOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Can&apos;t find campaign quest map data.
        /// </summary>
        internal static string Warning_MissingCampaignQuestMapData {
            get {
                return ResourceManager.GetString("Warning_MissingCampaignQuestMapData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Can&apos;t find crafting row {TableRow}.
        /// </summary>
        internal static string Warning_MissingCraftingTableRow {
            get {
                return ResourceManager.GetString("Warning_MissingCraftingTableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Curve table {Table} has no row {TableRow}.
        /// </summary>
        internal static string Warning_MissingCurveTableRow {
            get {
                return ResourceManager.GetString("Warning_MissingCurveTableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Can&apos;t find event quest map data.
        /// </summary>
        internal static string Warning_MissingEventQuestMapData {
            get {
                return ResourceManager.GetString("Warning_MissingEventQuestMapData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: No crafting row listed for schematic {Asset}.
        /// </summary>
        internal static string Warning_NoCraftingRowForSchematic {
            get {
                return ResourceManager.GetString("Warning_NoCraftingRowForSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: No stats located for schematic {SchematicId} (using prefix &apos;{TableRowPrefix}&apos;).
        /// </summary>
        internal static string Warning_NoStatsLocatedForSchematicUsingPrefix {
            get {
                return ResourceManager.GetString("Warning_NoStatsLocatedForSchematicUsingPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: No weapon/trap definition for crafting row {TableRow}.
        /// </summary>
        internal static string Warning_NoWeaponTrapDefinitionForCraftingRow {
            get {
                return ResourceManager.GetString("Warning_NoWeaponTrapDefinitionForCraftingRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: I don&apos;t know how to Override Percentage.
        /// </summary>
        internal static string Warning_OverridePercentageNotImplemented {
            get {
                return ResourceManager.GetString("Warning_OverridePercentageNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: No weapon/trap path indexed for {Asset}.
        /// </summary>
        internal static string Warning_UnindexedWeaponTrapPath {
            get {
                return ResourceManager.GetString("Warning_UnindexedWeaponTrapPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Unknown formatting style {FormattingStyle}.
        /// </summary>
        internal static string Warning_UnknownFormattingStyle {
            get {
                return ResourceManager.GetString("Warning_UnknownFormattingStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Crafting recipe with no matching schematic: {CraftingRecipeId}.
        /// </summary>
        internal static string Warning_UnmatchedCraftingRecipe {
            get {
                return ResourceManager.GetString("Warning_UnmatchedCraftingRecipe", resourceCulture);
            }
        }
    }
}
