//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanjoBotAssets.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BanjoBotAssets.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string ELanguage {
            get {
                return ResourceManager.GetString("ELanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load AES keys..
        /// </summary>
        internal static string Error_AesFetchFailed {
            get {
                return ResourceManager.GetString("Error_AesFetchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to merge because the previous artifact could not be read: {0}.
        /// </summary>
        internal static string Error_CannotReadPreviousArtifact {
            get {
                return ResourceManager.GetString("Error_CannotReadPreviousArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while processing asset {0}.
        /// </summary>
        internal static string Error_ExceptionWhileProcessingAsset {
            get {
                return ResourceManager.GetString("Error_ExceptionWhileProcessingAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while processing asset group {0}.
        /// </summary>
        internal static string Error_ExceptionWhileProcessingAssetGroup {
            get {
                return ResourceManager.GetString("Error_ExceptionWhileProcessingAssetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find game directory. Add it to the GameDirectories setting..
        /// </summary>
        internal static string Error_GameNotFound {
            get {
                return ResourceManager.GetString("Error_GameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load mappings..
        /// </summary>
        internal static string Error_MappingsFetchFailed {
            get {
                return ResourceManager.GetString("Error_MappingsFetchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a manager.
        /// </summary>
        internal static string Error_NotAManager {
            get {
                return ResourceManager.GetString("Error_NotAManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected manager synergy {0}.
        /// </summary>
        internal static string Error_UnexpectedManagerSynergy {
            get {
                return ResourceManager.GetString("Error_UnexpectedManagerSynergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender.
        /// </summary>
        internal static string Field_Defender_DefaultName {
            get {
                return ResourceManager.GetString("Field_Defender_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string Field_Defender_DisplayNameFormat {
            get {
                return ResourceManager.GetString("Field_Defender_DisplayNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Defender.
        /// </summary>
        internal static string Field_Defender_NameFormat {
            get {
                return ResourceManager.GetString("Field_Defender_NameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor.
        /// </summary>
        internal static string Field_Hero_Constructor {
            get {
                return ResourceManager.GetString("Field_Hero_Constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninja.
        /// </summary>
        internal static string Field_Hero_Ninja {
            get {
                return ResourceManager.GetString("Field_Hero_Ninja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No granted ability.
        /// </summary>
        internal static string Field_Hero_NoGrantedAbility {
            get {
                return ResourceManager.GetString("Field_Hero_NoGrantedAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlander.
        /// </summary>
        internal static string Field_Hero_Outlander {
            get {
                return ResourceManager.GetString("Field_Hero_Outlander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soldier.
        /// </summary>
        internal static string Field_Hero_Soldier {
            get {
                return ResourceManager.GetString("Field_Hero_Soldier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Field_Hero_Unknown {
            get {
                return ResourceManager.GetString("Field_Hero_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description.
        /// </summary>
        internal static string Field_NoDescription {
            get {
                return ResourceManager.GetString("Field_NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        internal static string Field_Recipe_Melee {
            get {
                return ResourceManager.GetString("Field_Recipe_Melee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged.
        /// </summary>
        internal static string Field_Recipe_Ranged {
            get {
                return ResourceManager.GetString("Field_Recipe_Ranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trap.
        /// </summary>
        internal static string Field_Recipe_Trap {
            get {
                return ResourceManager.GetString("Field_Recipe_Trap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assault.
        /// </summary>
        internal static string Field_Schematic_Assault {
            get {
                return ResourceManager.GetString("Field_Schematic_Assault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axe.
        /// </summary>
        internal static string Field_Schematic_Axe {
            get {
                return ResourceManager.GetString("Field_Schematic_Axe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceiling.
        /// </summary>
        internal static string Field_Schematic_Ceiling {
            get {
                return ResourceManager.GetString("Field_Schematic_Ceiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club.
        /// </summary>
        internal static string Field_Schematic_Club {
            get {
                return ResourceManager.GetString("Field_Schematic_Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crystal.
        /// </summary>
        internal static string Field_Schematic_Crystal {
            get {
                return ResourceManager.GetString("Field_Schematic_Crystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosive.
        /// </summary>
        internal static string Field_Schematic_Explosive {
            get {
                return ResourceManager.GetString("Field_Schematic_Explosive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        internal static string Field_Schematic_Floor {
            get {
                return ResourceManager.GetString("Field_Schematic_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware.
        /// </summary>
        internal static string Field_Schematic_Hardware {
            get {
                return ResourceManager.GetString("Field_Schematic_Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ore.
        /// </summary>
        internal static string Field_Schematic_Ore {
            get {
                return ResourceManager.GetString("Field_Schematic_Ore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pistol.
        /// </summary>
        internal static string Field_Schematic_Pistol {
            get {
                return ResourceManager.GetString("Field_Schematic_Pistol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scythe.
        /// </summary>
        internal static string Field_Schematic_Scythe {
            get {
                return ResourceManager.GetString("Field_Schematic_Scythe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shotgun.
        /// </summary>
        internal static string Field_Schematic_Shotgun {
            get {
                return ResourceManager.GetString("Field_Schematic_Shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMG.
        /// </summary>
        internal static string Field_Schematic_SMG {
            get {
                return ResourceManager.GetString("Field_Schematic_SMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sniper.
        /// </summary>
        internal static string Field_Schematic_Sniper {
            get {
                return ResourceManager.GetString("Field_Schematic_Sniper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spear.
        /// </summary>
        internal static string Field_Schematic_Spear {
            get {
                return ResourceManager.GetString("Field_Schematic_Spear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sword.
        /// </summary>
        internal static string Field_Schematic_Sword {
            get {
                return ResourceManager.GetString("Field_Schematic_Sword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Field_Schematic_Unknown {
            get {
                return ResourceManager.GetString("Field_Schematic_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall.
        /// </summary>
        internal static string Field_Schematic_Wall {
            get {
                return ResourceManager.GetString("Field_Schematic_Wall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survivor.
        /// </summary>
        internal static string Field_Survivor_DefaultName {
            get {
                return ResourceManager.GetString("Field_Survivor_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        internal static string Field_Survivor_Doctor {
            get {
                return ResourceManager.GetString("Field_Survivor_Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineer.
        /// </summary>
        internal static string Field_Survivor_Engineer {
            get {
                return ResourceManager.GetString("Field_Survivor_Engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        internal static string Field_Survivor_Explorer {
            get {
                return ResourceManager.GetString("Field_Survivor_Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gadgeteer.
        /// </summary>
        internal static string Field_Survivor_Gadgeteer {
            get {
                return ResourceManager.GetString("Field_Survivor_Gadgeteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventor.
        /// </summary>
        internal static string Field_Survivor_Inventor {
            get {
                return ResourceManager.GetString("Field_Survivor_Inventor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead {0}.
        /// </summary>
        internal static string Field_Survivor_LeadNameFormat {
            get {
                return ResourceManager.GetString("Field_Survivor_LeadNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marksman.
        /// </summary>
        internal static string Field_Survivor_Marksman {
            get {
                return ResourceManager.GetString("Field_Survivor_Marksman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martial Artist.
        /// </summary>
        internal static string Field_Survivor_MartialArtist {
            get {
                return ResourceManager.GetString("Field_Survivor_MartialArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer.
        /// </summary>
        internal static string Field_Survivor_Trainer {
            get {
                return ResourceManager.GetString("Field_Survivor_Trainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets.json.
        /// </summary>
        internal static string File_assets_json {
            get {
                return ResourceManager.GetString("File_assets_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schematics.json.
        /// </summary>
        internal static string File_schematics_json {
            get {
                return ResourceManager.GetString("File_schematics_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting game files.
        /// </summary>
        internal static string Status_DecryptingGameFiles {
            get {
                return ResourceManager.GetString("Status_DecryptingGameFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported item ratings.
        /// </summary>
        internal static string Status_ExportedItemRatings {
            get {
                return ResourceManager.GetString("Status_ExportedItemRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported recipes.
        /// </summary>
        internal static string Status_ExportedRecipes {
            get {
                return ResourceManager.GetString("Status_ExportedRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting {0}.
        /// </summary>
        internal static string Status_ExportingGroup {
            get {
                return ResourceManager.GetString("Status_ExportingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting item ratings.
        /// </summary>
        internal static string Status_ExportingItemRatings {
            get {
                return ResourceManager.GetString("Status_ExportingItemRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting recipes.
        /// </summary>
        internal static string Status_ExportingRecipes {
            get {
                return ResourceManager.GetString("Status_ExportingRecipes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching AES keys from external API: {0}.
        /// </summary>
        internal static string Status_FetchingAesFromApi {
            get {
                return ResourceManager.GetString("Status_FetchingAesFromApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} assets in {1} ({2} ms per asset).
        /// </summary>
        internal static string Status_LoadedAssets {
            get {
                return ResourceManager.GetString("Status_LoadedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading AES keys from {0}.
        /// </summary>
        internal static string Status_LoadingAesFromFile {
            get {
                return ResourceManager.GetString("Status_LoadingAesFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading localization.
        /// </summary>
        internal static string Status_LoadingLocalization {
            get {
                return ResourceManager.GetString("Status_LoadingLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading mappings.
        /// </summary>
        internal static string Status_LoadingMappings {
            get {
                return ResourceManager.GetString("Status_LoadingMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging into existing artifact: {0}.
        /// </summary>
        internal static string Status_MergingIntoExistingArtifact {
            get {
                return ResourceManager.GetString("Status_MergingIntoExistingArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cached AES keys found at {0}.
        /// </summary>
        internal static string Status_MissingAesCache {
            get {
                return ResourceManager.GetString("Status_MissingAesCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0} group {1} of {2}.
        /// </summary>
        internal static string Status_ProcessingTypeGroupNumOfNum {
            get {
                return ResourceManager.GetString("Status_ProcessingTypeGroupNumOfNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0} {1} of {2}.
        /// </summary>
        internal static string Status_ProcessingTypeNumOfNum {
            get {
                return ResourceManager.GetString("Status_ProcessingTypeNumOfNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering export types.
        /// </summary>
        internal static string Status_RegisteringExportTypes {
            get {
                return ResourceManager.GetString("Status_RegisteringExportTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrying mappings.
        /// </summary>
        internal static string Status_RetryingMappings {
            get {
                return ResourceManager.GetString("Status_RetryingMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caching AES keys in {0}.
        /// </summary>
        internal static string Status_SavingAesToFile {
            get {
                return ResourceManager.GetString("Status_SavingAesToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping {0} early as instructed..
        /// </summary>
        internal static string Status_SkippingEarlyAsInstructed {
            get {
                return ResourceManager.GetString("Status_SkippingEarlyAsInstructed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping gadget with no gameplay ability: {0}.
        /// </summary>
        internal static string Status_SkippingGadgetWithoutAbility {
            get {
                return ResourceManager.GetString("Status_SkippingGadgetWithoutAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping {0} late as instructed..
        /// </summary>
        internal static string Status_SkippingLateAsInstructed {
            get {
                return ResourceManager.GetString("Status_SkippingLateAsInstructed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping null {0} group containing {1} items..
        /// </summary>
        internal static string Status_SkippingNullGroup {
            get {
                return ResourceManager.GetString("Status_SkippingNullGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping group member that failed to parse: {0} ({1}).
        /// </summary>
        internal static string Status_SkippingUnparsable {
            get {
                return ResourceManager.GetString("Status_SkippingUnparsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting key for {0}.
        /// </summary>
        internal static string Status_SubmittingDynamicKey {
            get {
                return ResourceManager.GetString("Status_SubmittingDynamicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting main key.
        /// </summary>
        internal static string Status_SubmittingMainKey {
            get {
                return ResourceManager.GetString("Status_SubmittingMainKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing artifact: {0}.
        /// </summary>
        internal static string Status_WritingFreshArtifact {
            get {
                return ResourceManager.GetString("Status_WritingFreshArtifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Can&apos;t parse defender name: {0}.
        /// </summary>
        internal static string Warning_CannotParseDefenderName {
            get {
                return ResourceManager.GetString("Warning_CannotParseDefenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Can&apos;t determine PL requirement from objective condition: {0}.
        /// </summary>
        internal static string Warning_CannotParseDifficultyCondition {
            get {
                return ResourceManager.GetString("Warning_CannotParseDifficultyCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Can&apos;t parse hero name: {0}.
        /// </summary>
        internal static string Warning_CannotParseHeroName {
            get {
                return ResourceManager.GetString("Warning_CannotParseHeroName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Can&apos;t parse schematic name {0}.
        /// </summary>
        internal static string Warning_CannotParseSchematicName {
            get {
                return ResourceManager.GetString("Warning_CannotParseSchematicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Can&apos;t parse survivor name: {0}.
        /// </summary>
        internal static string Warning_CannotParseSurvivorName {
            get {
                return ResourceManager.GetString("Warning_CannotParseSurvivorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Could not load {0}.
        /// </summary>
        internal static string Warning_CouldNotLoadAsset {
            get {
                return ResourceManager.GetString("Warning_CouldNotLoadAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Could not find curve {0}.
        /// </summary>
        internal static string Warning_CouldNotLoadCurveTableRow {
            get {
                return ResourceManager.GetString("Warning_CouldNotLoadCurveTableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Failed to load {0}.
        /// </summary>
        internal static string Warning_FailedToLoadFile {
            get {
                return ResourceManager.GetString("Warning_FailedToLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Ignoring unknown modify operation {0}.
        /// </summary>
        internal static string Warning_IgnoringUnknownModifyOperation {
            get {
                return ResourceManager.GetString("Warning_IgnoringUnknownModifyOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Can&apos;t find crafting row {0}.
        /// </summary>
        internal static string Warning_MissingCraftingTableRow {
            get {
                return ResourceManager.GetString("Warning_MissingCraftingTableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Curve table has no row {0}.
        /// </summary>
        internal static string Warning_MissingCurveTableRow {
            get {
                return ResourceManager.GetString("Warning_MissingCurveTableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: No crafting row listed for schematic {0}.
        /// </summary>
        internal static string Warning_NoCraftingRowForSchematic {
            get {
                return ResourceManager.GetString("Warning_NoCraftingRowForSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: No weapon/trap definition for crafting row {0}.
        /// </summary>
        internal static string Warning_NoWeaponTrapDefinitionForCraftingRow {
            get {
                return ResourceManager.GetString("Warning_NoWeaponTrapDefinitionForCraftingRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: I don&apos;t know how to Override Percentage.
        /// </summary>
        internal static string Warning_OverridePercentageNotImplemented {
            get {
                return ResourceManager.GetString("Warning_OverridePercentageNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: {0} not found.
        /// </summary>
        internal static string Warning_SpecificAssetNotFound {
            get {
                return ResourceManager.GetString("Warning_SpecificAssetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: No weapon/trap path indexed for {0}.
        /// </summary>
        internal static string Warning_UnindexedWeaponTrapPath {
            get {
                return ResourceManager.GetString("Warning_UnindexedWeaponTrapPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Unknown formatting style {0}.
        /// </summary>
        internal static string Warning_UnknownFormattingStyle {
            get {
                return ResourceManager.GetString("Warning_UnknownFormattingStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Crafting recipe with no matching schematic: {0}.
        /// </summary>
        internal static string Warning_UnmatchedCraftingRecipe {
            get {
                return ResourceManager.GetString("Warning_UnmatchedCraftingRecipe", resourceCulture);
            }
        }
    }
}
